### ISSUE TITLE
Define Project Goals and Objectives

### ISSUE THREAD

**Issue by GoldenThrust** [EJmpa/Stat-Solver#4]
In this issue, we will define the overarching goals and specific objectives for our project. Clear project goals are essential to guide our work and measure our success. Please use this space to contribute and discuss what we aim to achieve with this project.

**Goals and Objectives:**
- [ ]  Describe the primary outcome we want to achieve.
- [ ]  List any secondary objectives or milestones.
- [ ]  Specify any success criteria or key performance indicators (KPIs).
- [ ]  Ensure alignment with the project's mission and vision.
- [ ]  Identify any constraints, limitations, or challenges we should be aware of.

**Comment by EJmpa** [comment]
Our objectives had been discussed in our several meetings.


- [ ] The goal right now is to carry data analysis on dataset
- [ ] Look out for features that affects the employability of Nigeria graduates
- [ ] Make Recommendations using insights gotten from the dataset
